Add validation and debugging

diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -22,9 +22,14 @@ elif [ "${MAX_LEVEL}" = 'file' ] && [ -z "$(plugin_read_config MANIFEST)" ]; the
   exit 1
 fi
 
+COMPRESS=$(plugin_read_config COMPRESSION 'none')
+if ! validate_compression "${COMPRESS}"; then
+  echo "+++ 🚨 Invalid value for compression level"
+  exit 1
+fi
+
 build_key "${MAX_LEVEL}" "${RESTORE_PATH}" # to validate the level
 
-COMPRESS=$(plugin_read_config COMPRESSION 'none')
 ACTUAL_PATH=$(mktemp)
 
 if [ "${COMPRESS}" = 'tgz' ]; then
@@ -48,6 +53,7 @@ for CURRENT_LEVEL in "${SORTED_LEVELS[@]}"; do
     backend_exec get "${KEY}" "${ACTUAL_PATH}"
 
     if [ "${COMPRESS}" != 'none' ]; then
+      echo "Cache is compressed, uncompressing..."
       "${UNCOMPRESS_COMMAND[@]}" "${ACTUAL_PATH}" "${RESTORE_PATH}"
     fi
 
diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -23,6 +23,10 @@ elif [ "${LEVEL}" = 'file' ] && [ -z "$(plugin_read_config MANIFEST)" ]; then
 fi
 
 COMPRESS=$(plugin_read_config COMPRESSION 'none')
+if ! validate_compression "${COMPRESS}"; then
+  echo "+++ 🚨 Invalid value for compression level"
+  exit 1
+fi
 
 KEY=$(build_key "${LEVEL}" "${CACHE_PATH}" "${COMPRESS}")
 
@@ -33,6 +37,7 @@ elif [ "${COMPRESS}" = 'zip' ]; then
 fi
 
 if [ "${COMPRESS}" != 'none' ]; then
+  echo "Compressing ${CACHE_PATH} with ${COMPRESS}..."
   ACTUAL_PATH=$(mktemp)
   "${COMPRESS_COMMAND[@]}" "${ACTUAL_PATH}" "${CACHE_PATH}"
 else
